//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnet.Portal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ApplicationSettingsDto xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <DefaultHighlightSettings>
    <HighlightSettingDto>
      <Regex>^(\[\d{2}\:\d{2}\:\d{2}[ ]VRB\][ ]|\d{2}\:\d{2}\:\d{2}[ ]\[VRB\][ ])</Regex>
      <Color>#808080</Color>
    </HighlightSettingDto>
    <HighlightSettingDto>
      <Regex>^(\[\d{2}\:\d{2}\:\d{2}[ ]INF\][ ]|\d{2}\:\d{2}\:\d{2}[ ]\[INF\][ ])</Regex>
      <Color>#008000</Color>
    </HighlightSettingDto>
    <HighlightSettingDto>
      <Regex>^(\[\d{2}\:\d{2}\:\d{2}[ ]DBG\][ ]|\d{2}\:\d{2}\:\d{2}[ ]\[DBG\][ ])</Regex>
      <Color>#00FFFF</Color>
    </HighlightSettingDto>
    <HighlightSettingDto>
      <Regex>^(\[\d{2}\:\d{2}\:\d{2}[ ]WRN\][ ]|\d{2}\:\d{2}\:\d{2}[ ]\[WRN\][ ])</Regex>
      <Color>#FFA500</Color>
    </HighlightSettingDto>
    <HighlightSettingDto>
      <Regex>^(\[\d{2}\:\d{2}\:\d{2}[ ]ERR\][ ]|\d{2}\:\d{2}\:\d{2}[ ]\[ERR\][ ])</Regex>
      <Color>#FF0000</Color>
    </HighlightSettingDto>
    <HighlightSettingDto>
      <Regex>^(\[\d{2}\:\d{2}\:\d{2}[ ]FTL\][ ]|\d{2}\:\d{2}\:\d{2}[ ]\[FTL\][ ])</Regex>
      <Color>#9370DB</Color>
    </HighlightSettingDto>
  </DefaultHighlightSettings>
</ApplicationSettingsDto>")]
        public string DefaultSettings {
            get {
                return ((string)(this["DefaultSettings"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserSettings {
            get {
                return ((string)(this["UserSettings"]));
            }
            set {
                this["UserSettings"] = value;
            }
        }
    }
}
